blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView  #, toggle_publish

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', never_cache(PostListView.as_view()), name='post_list'),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name='post_item'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('posts/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('posts/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    # path('posts/toggle/<slug>/', toggle_publish, name='toggle_publish')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('skychimp/', include('skychimp.urls', namespace='skychimp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import itertools

from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    name = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.SlugField(max_length=150, db_index=True, verbose_name='URL', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='images/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    published = models.BooleanField(verbose_name='признак публикации', default=True)
    view_count = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return f'{self.name}'

    # def save(self, *args, **kwargs):
    #     eng_title = translit(self.name, 'ru', reversed=True)
    #     self.slug = slugify(eng_title, allow_unicode=True)
    #     super(Post, self).save(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()
        return super().save(*args, **kwargs)

    def _generate_slug(self):
        slug_candidate = slugify(self.name)
        if not slug_candidate:
            slug_candidate = "s"
        for i in itertools.count(1):
            if not Post.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_candidate, i)
        self.slug = slug_candidate
        return self.slug

    def get_absolute_url(self):
        return reverse('blog:post_item', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('created_at',)

    def increase_view_count(self):
        """
        Увеличивает просмотры поста на 1.
        """
        self.view_count += 1
        self.save()

blog/views.py
# Create your views here.
# from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, \
    UpdateView, DeleteView  # , DetailView, CreateView, UpdateView, DeleteView
# from django.urls import reverse_lazy, reverse

from blog.models import Post


class PostListView(ListView):
    model = Post
    extra_context = {
        'object_list': Post.objects.all(),
        'title': 'Все статьи'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)
        return queryset


class PostDetailView(DetailView):
    model = Post

    def get_object(self, **kwargs):
        views = super().get_object()
        views.increase_view_count()
        return views


class PostCreateView(CreateView):
    model = Post
    fields = ('name', 'content', 'image', 'published')
    success_url = reverse_lazy('blog:post_list', )


class PostUpdateView(UpdateView):
    model = Post
    fields = ('name', 'slug', 'content', 'image', 'published')

    def get_success_url(self):
        return reverse('blog:post_item', kwargs={'slug': self.object.slug})


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


# def toggle_publish(pk):
#     post_item = get_object_or_404(Post, pk=pk)
#     if post_item.published:
#         post_item.published = False
#     else:
#         post_item.published = True
#
#     post_item.save()
#
#     return redirect(reverse('blog:blog_item', args=[post_item.pk]))

blog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены, что хотите удалить продукт "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}


{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <img src="{% mediapath object.image %}" alt="Картинка" width="200" height="200"/>
                    <tr>
                        <td>Заголовок</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td>Содержимое</td>
                        <td>{{ object.content }}</td>
                    </tr>

                    <tr>
                        <td>Дата публикации</td>
                        <td>{{ object.created_at }}</td>
                    </tr>
                    <tr>
                        <td>Количество просмотров</td>
                        <td>{{ object.view_count }}</td>
                    </tr>

                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary"><< Назад</a>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Публикации</h1>
    </div>

    <div class="col-12">
        <a href="{% url 'blog:post_create' %}" class="btn btn-primary">Создать публикацию</a>
    </div>

    <div class="container">
        {% if object_list %}
            <div class="row text-center">
                {% for object in object_list %}
                    {% include 'blog/includes/inc_post_card.html' %}
                {% endfor %}
            </div>
        {% else %}
            <h3>Публикаций нет</h3>
        {% endif %}
    </div>
{% endblock %}