blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView  #, toggle_publish

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', never_cache(PostListView.as_view()), name='post_list'),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name='post_item'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('posts/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('posts/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    # path('posts/toggle/<slug>/', toggle_publish, name='toggle_publish')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import home, info, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionListView, CategoriesListView

app_name = CatalogConfig.name
urlpatterns = [

    path('', home, name='home'),
    path('contacts/', info, name='contacts'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/versions/<int:pk>/', VersionListView.as_view(), name='version'),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('skychimp/', include('skychimp.urls', namespace='skychimp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skychimp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache, cache_page

from catalog.apps import CatalogConfig
from skychimp.apps import SkychimpConfig
from skychimp.views import *

app_name = SkychimpConfig.name


urlpatterns = [
    path('', never_cache(IndexView.as_view()), name='Index'),
    path('customer/', never_cache(CustomerListView.as_view()), name='customer_list'),
    path('<int:pk>/', cache_page(60)(CustomerDetailView.as_view()), name='customer_view'),
    path('customer/create/', cache_page(60)(CustomerCreateView.as_view()), name='customer_create'),
    path('customer/update/<int:pk>/', cache_page(60)(CustomerUpdateView.as_view()), name='customer_update'),
    path('customer/delete/<int:pk>/', cache_page(60)(CustomerDeleteView.as_view()), name='customer_delete'),
    path('message/', never_cache(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_view'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('sending/', never_cache(SendingListView.as_view()), name='sending_list'),
    path('sending/<int:pk>/', SendingDetailView.as_view(), name='sending_view'),
    path('sending/create/', SendingCreateView.as_view(), name='sending_create'),
    path('sending/update/<int:pk>/', SendingUpdateView.as_view(), name='sending_update'),
    path('sending/delete/<int:pk>/', SendingDeleteView.as_view(), name='sending_delete'),
    path('attempt/', never_cache(AttemptListView.as_view()), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_view'),
    path('set_is_active/<int:pk>', login_required(set_is_active), name='set_is_active'),
    path('set_status_sending/<int:pk>', login_required(set_status_sending), name='set_status_sending')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from skychimp.views import set_is_active
from users.apps import UsersConfig
from users.views import ProfileUpdateView, UserRegisterView, EmailConfirmationSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmationFailedView, generate_new_password, backup_pass

app_name = UsersConfig.name

urlpatterns = [

    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('generate_new_password/', generate_new_password, name='generate_new_password'),
    path('backup_pass/', backup_pass, name='backup_pass'),
    # path('activate/<str:token>/', activate_user, name='activate'),
    # path('page_after_registration/<str:token>/', page_after_registration, name='page_after_registration'),
    # path('backup_pass/', PasswordChangeView_.as_view(), name='backup_pass'),

]

catalog/models.py
from django.db import models

from users.models import User

# from catalog.models import Product


# Create your models here.
NULLABLE = {'blank': True, 'null': True}


# class ProductListView(generic.ListView):
#     model = Product

class Product(models.Model):
    ACTIV = 'Активна'
    NO_ACTIV = 'Не активна'

    SELECT_STATUS = [
        (ACTIV, 'Активна'),
        (NO_ACTIV, 'Не активна'),
    ]





    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='media', verbose_name='фото', **NULLABLE)
    category = models.CharField(max_length=150, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date_create = models.DateTimeField(verbose_name='дата создания')
    date_change = models.DateTimeField(verbose_name='дата изменения')
    status = models.CharField(max_length=50, default=NO_ACTIV, choices=SELECT_STATUS, verbose_name='Статус')
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    # creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель', **NULLABLE, default=email)
    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    name_of_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='наименование')
    number_of_version = models.CharField(max_length=150, verbose_name='номер версии')
    title_of_version = models.CharField(max_length=150, verbose_name='имя версии')
    actual_version = models.BooleanField(verbose_name='актуальность версии', default=True)

    def __str__(self):
        return f'{self.title_of_version} ({self.name_of_product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class FormStyleMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price',)

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        for word in self.forbidden_words:
            if word in cleaned_name.lower():
                raise forms.ValidationError(f'Название не может содержать слово "{word}"')
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in cleaned_description.lower():
                raise forms.ValidationError(f'Описание не может содержать слово "{word}"')
        return cleaned_description


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
import os

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import ListView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_subjects
from config import settings

# @login_required
# @permission_required('main:view_product')
def home(request):
    path = settings.MEDIA_ROOT
    img_list = os.listdir(path + '/images')
    extra_context = {
        'product_list': Product.objects.all()[:3],
        'title': 'Главная',
        'images': img_list,
        'object_list': Product.objects.filter(status='Активна')
    }
    return render(request, 'catalog/home.html', extra_context)


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    extra_context = {'title': 'Список продукции', 'object_list': Product.objects.filter(status='Активна')}

    def get_object(self, queryset=None):
        return self.request.user
# def products(request):
#     path = settings.MEDIA_ROOT
#     img_list = os.listdir(path + '/images')
#     context = {
#         'product_list': Product.objects.all(),
#         'title': 'Список продукции',
#         'images': img_list
#     }
#     return render(request, 'catalog/product_list.html', context)
class ProductDetailView(LoginRequiredMixin,  generic.DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        #context_data['description'] = self.get_object()
        context_data['versions'] = Version.objects.filter(name_of_product=self.object, actual_version=True)
        return context_data
    # def get_object(self, queryset=None):
    #     return self.request.user

# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item,
#         'title': product_item
#     }
#     return render(request, 'catalog/product_detail.html', context)

class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Product
    fields = ('name', 'description', 'preview', 'category', 'price', 'date_create', 'date_change', 'status', 'creator')
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.add_product'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    # def get_object(self, queryset=None):
    #     return self.request.user

class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form_with_formset.html'
    #fields = ('name', 'description', 'preview', 'category', 'price', 'date_create', 'date_change')
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.change_product'

    def get_success_url(self, *args, **kwargs):
        return reverse('main:product_update', args=[self.get_object().pk])

    def get_object(self, queryset=None):  # продукт должен редактировать только владелец
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    # def get_object(self, queryset=None):
    #     return self.request.user
class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('main:product_list')
    def test_func(self):
        return self.request.user.is_superuser

    def get_object(self, queryset=None):
        return self.request.user
class VersionListView(ListView):
    model = Version

class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):   # меняет title на __str__.object (имя студента)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_subjects    # логика вынесена в services.py ---------
        return context_data

# @login_required
def info(request):
    context = {
        'title': 'Контакты',

    }
    return render(request, 'catalog/info.html')

catalog/templates/catalog/includes/inc_category_card.html
<div class="card shadow-sm">
    <div class="card-body">
        <h1>{{ category.name }}</h1>
        <p class="card-text">{{ category.description }}</p>
    </div>
</div>

catalog/templates/catalog/includes/inc_main_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Sending Service</h5>
        <nav class="ms-5">


            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'main:home' %}">Главная</a>
{#                <a class="p-2 btn btn-outline-primary" href="{% url 'main:product_list' %}">Продукция</a>#}
{#                <a class="p-2 btn btn-outline-primary" href="{% url 'main:categories_list' %}">Категории</a>#}
{#                <a class="p-2 btn btn-outline-primary" href="{% url 'skychimp:index' %}">skychimp</a>#}
                <a class="p-2 btn btn-outline-primary" href="{% url 'skychimp:customer_list' %}">Клиенты</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'skychimp:message_list' %}">Сообщения</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'skychimp:sending_list' %}">Рассылки</a>
{#                <a class="p-2 btn btn-outline-primary" href="{% url 'main:contacts' %}">Контакты</a>#}
                <a class="p-2 btn btn-outline-primary" href="{% url 'skychimp:attempt_list' %}">Статистика</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'blog:post_list' %}">Блог</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>

            {% endif %}
        </nav>
    </div>
</head>
<body>

</body>
</html>

catalog/templates/catalog/includes/inc_product_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <meta charset="UTF-8">
    {#    <title>{{ title }}</title>#}
    {% for object in product_list %}
        <div class="col-lg-4">
            <div class="card m-2 text-center">
                <div class="card-body">
                    {#            <img src="{% static "/media/images/apple.jpg" %}" alt="My image">#}
                    {% if  object.preview %}
                        <img src={{ object.preview.url }} class="rounded-circle" alt={{ object.name }} width="140"
                             height="140">
                    {% endif %}

                    {#            <img src="{{ object.preview.url }}"  alt="image">#}
                    {#            <img class="rounded-circle"#}
                    {#                 src="{% object.preview.url %}"#}
                    {#                 alt="Generic placeholder image" width="140" height="140">#}
                    <h2>{{ object.name | title }}</h2>
                    <p>{{ object.description | title }}</p>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                        {% for version in object.version_set.all %}
                            {% if version.actual_version %}

                                <div><strong>Активная версия: </strong> {{ version.number_of_version }}
                                    - {{ version.title_of_version }}</div>
                            {% endif %}
                        {% endfor %}

                    </ul>
                    {% if user.is_authenticated %}
{#                    {% if perms.main.view_product %}#}
                    <p><a class="btn btn-secondary" href="{% url 'main:product_item' object.pk %}" role="button">Подробнее
                        >></a></p>
{#                    {% endif %}#}
{#                    {% if user.is_authenticated and object.user == user.email %}#}
{#                    {% if perms.main.change_product %}#}
{#                    {% if user.email == product.user %}#}
{#                        {% if object.user == user.email %}#}
{#                        {% if perms.catalog.change_product and product.object.creator == object.user.email %}#}
                    {% if user.email == object.user %}
                    <p><a class="btn btn-warning" href="{% url 'main:product_update' object.pk %}" role="button">Редактировать
                        >></a></p>
                    {% endif %}
{#                    {% endif %}#}
                    {% if user.is_superuser %}
                    <p><a class="btn btn-danger" href="{% url 'main:product_delete' object.pk %}" role="button">Удалить>></a></p>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>

    {% endfor %}



</body>
</html>