blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView  #, toggle_publish

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', never_cache(PostListView.as_view()), name='post_list'),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name='post_item'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('posts/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('posts/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    # path('posts/toggle/<slug>/', toggle_publish, name='toggle_publish')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('skychimp/', include('skychimp.urls', namespace='skychimp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skychimp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache, cache_page

from catalog.apps import CatalogConfig
from skychimp.apps import SkychimpConfig
from skychimp.views import *

app_name = SkychimpConfig.name


urlpatterns = [
    path('', never_cache(IndexView.as_view()), name='Index'),
    path('customer/', never_cache(CustomerListView.as_view()), name='customer_list'),
    path('<int:pk>/', cache_page(60)(CustomerDetailView.as_view()), name='customer_view'),
    path('customer/create/', cache_page(60)(CustomerCreateView.as_view()), name='customer_create'),
    path('customer/update/<int:pk>/', cache_page(60)(CustomerUpdateView.as_view()), name='customer_update'),
    path('customer/delete/<int:pk>/', cache_page(60)(CustomerDeleteView.as_view()), name='customer_delete'),
    path('message/', never_cache(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_view'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('sending/', never_cache(SendingListView.as_view()), name='sending_list'),
    path('sending/<int:pk>/', SendingDetailView.as_view(), name='sending_view'),
    path('sending/create/', SendingCreateView.as_view(), name='sending_create'),
    path('sending/update/<int:pk>/', SendingUpdateView.as_view(), name='sending_update'),
    path('sending/delete/<int:pk>/', SendingDeleteView.as_view(), name='sending_delete'),
    path('attempt/', never_cache(AttemptListView.as_view()), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_view'),
    path('set_is_active/<int:pk>', login_required(set_is_active), name='set_is_active'),
    path('set_status_sending/<int:pk>', login_required(set_status_sending), name='set_status_sending')
]

skychimp/models.py
from django.db import models
from datetime import date, datetime
NULLABLE = {'null': True, 'blank': True}


class Customer(models.Model):
    name = models.CharField(max_length=150, verbose_name='имя', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='почта', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    created_by = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Кем создан',
                                   related_name='client', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=254, verbose_name='Тема')
    body = models.TextField(verbose_name='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Sending(models.Model):
    ONCE = 'Один раз'
    DAILY = '1 раз в день'
    WEEKLY = '1 раз в неделю'
    MONTHLY = '1 раз в месяц'

    FREQUENCY_CHOICES = [

        (ONCE, 'Один раз'),
        (DAILY, '1 раз в день'),
        (WEEKLY, '1 раз в неделю'),
        (MONTHLY, '1 раз в месяц'),
    ]
    CREATED = 'Создана'
    COMPLETED = 'Завершена'
    LAUNCHED = 'Запущена'

    SELECT_STATUS = [
        (CREATED, 'Создана'),
        (COMPLETED, 'Завершена'),
        (LAUNCHED, 'Запущена'),
    ]

    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    # created_at = models.DateTimeField(auto_now_add=True)
    scheduled_time = models.TimeField(default=datetime.now, verbose_name='Время рассылки')
    start_date = models.DateField(default=date.today, verbose_name='Дата начала')
    end_date = models.DateField(default=date.today, verbose_name='Дата окончания')
    frequency = models.CharField(max_length=14, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, default='Создана', choices=SELECT_STATUS, verbose_name='Статус')
    created = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Кем создано',
                                related_name='clients', **NULLABLE)

    def __str__(self):
        return self.message.subject

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('set_send_status', 'Can set sending status'),
                ]


class Attempt(models.Model):
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    sending = models.ForeignKey(Sending, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    sent_at = models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки')
    status = models.CharField(choices=STATUS, verbose_name='Статус')
    response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        return f"{self.sending.message.subject} - {self.sent_at}"

    class Meta:
        verbose_name = 'Статистика (попытка)'
        verbose_name_plural = 'Статистики (попытки)'

skychimp/views.py
from random import sample

import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from blog.models import Post
from skychimp.models import *
from skychimp.services import send_email


class IndexView(TemplateView):
    template_name = 'skychimp/skychimp_index.html'
    extra_context = {
        'title': 'Главная страница',
        'object_list': Sending.objects.all()
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_posts = list(Post.objects.all())
        context['random_blog_posts'] = sample(all_posts, min(3, len(all_posts)))
        return context


class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer
    extra_context = {
        'object_list': Customer.objects.all(),
        'title': 'Все клиенты'  # дополнение к статической информации
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('skychimp.view_client'):
            return queryset
        return Customer.objects.filter(created_by=self.request.user)


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer


class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    fields = ('name', 'email', 'comment', 'created_by',)
    success_url = reverse_lazy('skychimp:customer_list')


class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Customer
    fields = ('name', 'email', 'comment', 'created_by', 'is_active',)

    def get_success_url(self):
        return reverse('skychimp:customer_view', args=[str(self.object.pk)])


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('skychimp:customer_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'message_list': Message.objects.all(),
        'title': 'Все Сообщения'  # дополнение к статической информации
    }


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('skychimp:message_list')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ('subject', 'body',)

    def get_success_url(self):
        return reverse('skychimp:sending_view', args=[str(self.object.pk)])


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('skychimp:message_list')


class SendingListView(LoginRequiredMixin, ListView):
    model = Sending
    extra_context = {
        'object_list': Sending.objects.all(),
        'title': 'Все Рассылки'  # дополнение к статической информации
    }
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('skychimp.view_sending'):
            return queryset
        return Sending.objects.filter(created=self.request.user)


class SendingDetailView(LoginRequiredMixin, DetailView):
    model = Sending


class SendingCreateView(LoginRequiredMixin, CreateView):
    model = Sending
    fields = ('message', 'frequency', 'status', 'created', 'scheduled_time', 'start_date', 'end_date',)
    success_url = reverse_lazy('skychimp:sending_list')
    try:
        for send in Sending.objects.all():
            if send.status == Sending.CREATED:
                send_email(Sending.ONCE)
    except django.db.utils.ProgrammingError:
        print('ProgrammingError')


class SendingUpdateView(LoginRequiredMixin, UpdateView):
    model = Sending
    fields = ('message', 'frequency', 'status',)

    def get_success_url(self):
        return reverse('skychimp:sending_view', args=[str(self.object.pk)])


class SendingDeleteView(LoginRequiredMixin, DeleteView):
    model = Sending
    success_url = reverse_lazy('skychimp:sending_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    extra_context = {
        'object_list': Attempt.objects.all(),
        'title': 'Все Рассылки'  # дополнение к статической информации
    }


class AttemptDetailView(DetailView):
    model = Attempt


def set_is_active(request, pk):
    customer_item = get_object_or_404(Customer,
                                      pk=pk)  # get_object_or_404 ищет объект модели если не находит выводит ошибку
    if customer_item.is_active:
        customer_item.is_active = False
    else:
        customer_item.is_active = True
    customer_item.save()
    return redirect(reverse('skychimp:customer_list'))


def set_status_sending(request, pk):
    sending_item = get_object_or_404(Sending,
                                     pk=pk)  # get_object_or_404 ищет объект модели если не находит выводит ошибку
    if sending_item.status == Sending.CREATED:
        sending_item.status = Sending.COMPLETED
        sending_item.save()
    else:
        sending_item.status = Sending.CREATED
        sending_item.save()
    return redirect(reverse('skychimp:sending_list'))

skychimp/templates/skychimp/attempt_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="card">

        <div class="card-header">{{ object.sending }}</div>
        <div class="card-body">
            <table class="table table-striped">
                              <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.sent_at }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title">{{ object.status }}</h6>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.response }}</li>
                        </ul>
                    </div>
                </div>
            </table>
        </div>
        <div class="card-footer">
            <a href="{% url 'skychimp:customer_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">назад</a>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/attempt_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for object in object_list %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h5 class="my-0 fw-normal">{{ object.sending }}</h5>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.sent_at }}</li>
                            </ul>
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.status }}</li>
                            </ul>
                            <p><a class="btn btn-secondary" href="{% url 'skychimp:attempt_view' object.pk %}">Посмотреть
                                &raquo;</a></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

skychimp/templates/skychimp/customer_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены что хотите удалить запись "{{ object }}"?<br> <br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:customer_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/customer_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %} Создать {% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:customer_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/customer_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">
                <a href="{% url 'skychimp:customer_create' %}" class="btn btn-primary m-2">Создать клиента</a>
            </div>
            {% for object in object_list %}
                {% if user.is_authenticated and object.created_by == user or user.is_superuser or user.is_staff %}
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-3">
                                <h5 class="my-0 fw-normal">{{ object.name }}</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title pricing-card-title">{{ object.email }}</h6>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.message }}</li>
                                </ul>
                                <p><a class="btn btn-secondary" href="{% url 'skychimp:customer_view' object.pk %}">Посмотреть
                                    &raquo;</a></p>
                                {% if user.is_authenticated and object.created_by == user or user.is_superuser %}
                                    <p><a class="btn btn-warning" href="{% url 'skychimp:customer_update' object.pk %}">Изменить
                                        &raquo;</a></p>
                                    <p><a class="btn btn-danger" href="{% url 'skychimp:customer_delete' object.pk %}">Удалить
                                        &raquo;</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </main>
{% endblock %}

skychimp/templates/skychimp/message_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены что хотите удалить запись "{{ object }}"?<br> <br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:message_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/message_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">{{ object.subject }}</div>
        <div class="card-body">
            <table class="table table-striped">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.name }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title">{{ object.body }}</h6>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.created_at }}</li>
                        </ul>
                    </div>
                </div>
            </table>
        </div>
        <div class="card-footer">
            <a href="{% url 'skychimp:message_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">назад</a>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/message_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %} Создать {% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:message_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/message_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">
                <a href="{% url 'skychimp:message_create' %}" class="btn btn-primary m-2">Создать сообщение</a>
            </div>
            {% for object in message_list %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h5 class="my-0 fw-normal">{{ object.subject }}</h5>
                        </div>
                        <div class="card-body">
                            <h6 class="card-title pricing-card-title">{{ object.body }}</h6>
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.created_at }}</li>
                            </ul>
                            <p><a class="btn btn-secondary" href="{% url 'skychimp:message_view' object.pk %}">Посмотреть
                                &raquo;</a></p>
                            <p><a class="btn btn-warning" href="{% url 'skychimp:message_update' object.pk %}">Изменить
                                &raquo;</a></p>
                            <p><a class="btn btn-danger" href="{% url 'skychimp:message_delete' object.pk %}">Удалить
                                &raquo;</a></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

skychimp/templates/skychimp/sending_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены что хотите удалить запись "{{ object }}"?<br> <br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:sending_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/sending_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">{{ object.message }}</div>
        <div class="card-body">
            <table class="table table-striped">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.created_at }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title">{{ object.scheduled_time }}</h6>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.frequency }}</li>
                        </ul>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.status }}</li>
                        </ul>
                    </div>
                </div>
            </table>
        </div>
        <a href="{% url 'skychimp:set_status_sending' object.pk %}" class="btn btn-outline-warning float-end">
            {% if object.CREATED %}
                Деактивировать
            {% else %}
                Активировать
            {% endif %}
        </a>
        <div class="card-footer">
            <a href="{% url 'skychimp:sending_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">назад</a>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/sending_form.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %} Создать {% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'skychimp:sending_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

skychimp/templates/skychimp/sending_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">
                <a href="{% url 'skychimp:sending_create' %}" class="btn btn-primary m-2">Создать рассылку</a>
            </div>

            {% for object in object_list %}
                {% if user.is_authenticated and object.created_by == user or user.is_superuser or user.is_staff %}
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-3">
                                <h5 class="my-0 fw-normal">{{ object.message }}</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title pricing-card-title">{{ object.created_at }}</h6>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.scheduled_time }}</li>
                                </ul>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.frequency }}</li>
                                </ul>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.status }}</li>
                                </ul>
                                <p><a class="btn btn-secondary" href="{% url 'skychimp:sending_view' object.pk %}">Посмотреть
                                    &raquo;</a></p>
                                {% if user.is_authenticated and object.created_by == user or user.is_superuser %}
                                    <p><a class="btn btn-warning" href="{% url 'skychimp:sending_update' object.pk %}">Изменить
                                        &raquo;</a></p>
                                    <p><a class="btn btn-danger" href="{% url 'skychimp:sending_delete' object.pk %}">Удалить
                                        &raquo;</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </main>
{% endblock %}

skychimp/templates/skychimp/skychimp_index.html
{% extends 'catalog/base.html' %}

{% load sending_count %}
{% load active_sending_count %}
{% load active_customer_count %}
{% block content %}

    <div class="row gy-5">
        <h5> Сервис рассылки сообщений</h5>

        <div class="col">
            <div class="card shadow-sm text-center" style="background: #e0e0e0">
                <figure class="p-3 mb-0">
                    Создано рассылок: {% sending_count %}.<br>
                    <br>
                    Количество активных рассылок: {% active_sending_count %}.<br>
                    <br>
                    Количество уникальных клиентов: {% active_customer_count %}
                </figure>
            </div>
        </div>
        {% for object in random_blog_posts %}
            {% include 'blog/includes/inc_post_card.html' %}
        {% endfor %}
    </div>

{% endblock %}