blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView  #, toggle_publish

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', never_cache(PostListView.as_view()), name='post_list'),
    path('posts/<slug:slug>/', PostDetailView.as_view(), name='post_item'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('posts/update/<slug:slug>/', PostUpdateView.as_view(), name='post_update'),
    path('posts/delete/<slug:slug>/', PostDeleteView.as_view(), name='post_delete'),
    # path('posts/toggle/<slug>/', toggle_publish, name='toggle_publish')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import home, info, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, VersionListView, CategoriesListView

app_name = CatalogConfig.name
urlpatterns = [

    path('', home, name='home'),
    path('contacts/', info, name='contacts'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/versions/<int:pk>/', VersionListView.as_view(), name='version'),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('skychimp/', include('skychimp.urls', namespace='skychimp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

# from catalog.models import Product


# Create your models here.
NULLABLE = {'blank': True, 'null': True}


# class ProductListView(generic.ListView):
#     model = Product

class Product(models.Model):
    ACTIV = 'Активна'
    NO_ACTIV = 'Не активна'

    SELECT_STATUS = [
        (ACTIV, 'Активна'),
        (NO_ACTIV, 'Не активна'),
    ]





    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='media', verbose_name='фото', **NULLABLE)
    category = models.CharField(max_length=150, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date_create = models.DateTimeField(verbose_name='дата создания')
    date_change = models.DateTimeField(verbose_name='дата изменения')
    status = models.CharField(max_length=50, default=NO_ACTIV, choices=SELECT_STATUS, verbose_name='Статус')
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    # creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель', **NULLABLE, default=email)
    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    name_of_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='наименование')
    number_of_version = models.CharField(max_length=150, verbose_name='номер версии')
    title_of_version = models.CharField(max_length=150, verbose_name='имя версии')
    actual_version = models.BooleanField(verbose_name='актуальность версии', default=True)

    def __str__(self):
        return f'{self.title_of_version} ({self.name_of_product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class FormStyleMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price',)

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        for word in self.forbidden_words:
            if word in cleaned_name.lower():
                raise forms.ValidationError(f'Название не может содержать слово "{word}"')
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in cleaned_description.lower():
                raise forms.ValidationError(f'Описание не может содержать слово "{word}"')
        return cleaned_description


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
import os

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import ListView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_subjects
from config import settings

# @login_required
# @permission_required('main:view_product')
def home(request):
    path = settings.MEDIA_ROOT
    img_list = os.listdir(path + '/images')
    extra_context = {
        'product_list': Product.objects.all()[:3],
        'title': 'Главная',
        'images': img_list,
        'object_list': Product.objects.filter(status='Активна')
    }
    return render(request, 'catalog/home.html', extra_context)


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    extra_context = {'title': 'Список продукции', 'object_list': Product.objects.filter(status='Активна')}

    def get_object(self, queryset=None):
        return self.request.user
# def products(request):
#     path = settings.MEDIA_ROOT
#     img_list = os.listdir(path + '/images')
#     context = {
#         'product_list': Product.objects.all(),
#         'title': 'Список продукции',
#         'images': img_list
#     }
#     return render(request, 'catalog/product_list.html', context)
class ProductDetailView(LoginRequiredMixin,  generic.DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        #context_data['description'] = self.get_object()
        context_data['versions'] = Version.objects.filter(name_of_product=self.object, actual_version=True)
        return context_data
    # def get_object(self, queryset=None):
    #     return self.request.user

# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object': product_item,
#         'title': product_item
#     }
#     return render(request, 'catalog/product_detail.html', context)

class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Product
    fields = ('name', 'description', 'preview', 'category', 'price', 'date_create', 'date_change', 'status', 'creator')
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.add_product'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    # def get_object(self, queryset=None):
    #     return self.request.user

class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form_with_formset.html'
    #fields = ('name', 'description', 'preview', 'category', 'price', 'date_create', 'date_change')
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.change_product'

    def get_success_url(self, *args, **kwargs):
        return reverse('main:product_update', args=[self.get_object().pk])

    def get_object(self, queryset=None):  # продукт должен редактировать только владелец
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    # def get_object(self, queryset=None):
    #     return self.request.user
class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('main:product_list')
    def test_func(self):
        return self.request.user.is_superuser

    def get_object(self, queryset=None):
        return self.request.user
class VersionListView(ListView):
    model = Version

class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):   # меняет title на __str__.object (имя студента)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_subjects    # логика вынесена в services.py ---------
        return context_data

# @login_required
def info(request):
    context = {
        'title': 'Контакты',

    }
    return render(request, 'catalog/info.html')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}

<main role="main">
    <!-- Three columns of text below the carousel -->
    <h1>{{ title }}</h1>
    <div class="row">
        {% block content %}
        {% endblock %}

    </div><!-- /.col-lg-4 -->
</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    {% for category in category_list %}
        {% include 'catalog/includes/inc_category_card.html' %}
    {% endfor %}
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load sending_count %}
{% load active_sending_count %}
{% load active_customer_count %}

<body>
{% block content %}
    {% if user.is_authenticated %}
        <div class="heading-text">
        <div class="col-6">
            <h5> Сервис рассылки сообщений</h5>
        </div>
            <div class="col">
                <div class="card shadow-sm text-center" style="background: #e0e0e0">
                    <figure class="p-3 mb-0">
                        Создано рассылок: {% sending_count %}.<br>
                        <br>
                        Количество активных рассылок: {% active_sending_count %}.<br>
                        <br>
                        Количество уникальных клиентов: {% active_customer_count %}
                    </figure>
                </div>
            </div>
        <div class="col-12">
            {% for object in random_blog_posts %}
                {% include 'blog/includes/inc_post_card.html' %}
            {% endfor %}
        </div>
        </div>
    {% else %}
        Вы не авторизованы
    {% endif %}
{% endblock %}

{#{% block content %}#}
{#    {% if user.is_authenticated %}#}
{#    {% include 'catalog/includes/inc_product_card.html' %}#}
{#    {% else %}#}
{#    Вы не авторизованы#}
{#    {% endif %}#}
{#{% endblock %}#}
</body>

catalog/templates/catalog/info.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
<div class="card">
    <div class="card-body">
       <form method="post">
           {% csrf_token %}
           Уверены, что хотите удалить товар "{{ object }}"?<br>
           <input type="submit" class="btn btn-outline-danger" value="Уверен">
       </form>
    </div>
    <div class="card-footer">
        <a href="{% url 'main:product_list' %}" class="btn btn-primary">Назад к списку</a>
    </div>
</div>
</div>
    {% include 'catalog/includes/inc_product_card.html' %}
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}
<div class="col">
<div class="card">
    <div class="card-body">
        <table class="table">
             <img src="{% mediapath object.image %}" alt="Картинка" width="200" height="200"/>
            <tr>
                <td>Наименование</td>
                <td>{{ object.name }}</td>
            </tr>
             <tr>
                <td>Описание</td>
                <td>{{ object.description }}</td>
            </tr>
        </table>
    </div>
    <div class="card-footer">
        <a href="{% url 'main:product_list' %}" class="btn btn-primary">Назад к списку</a>
    </div>
</div>
</div>
    {% include 'catalog/includes/inc_product_card.html' %}
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    Добавление продукции
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary"
                           value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:product_list' %}" class="btn btn-primary">Назад к списку</a>
            </div>
        </div>
    </div>
{#    {% include 'catalog/includes/inc_product_card.html' %}#}
{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <form class="row" method="post">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Сохранить{% else %}Создать{% endif %}">

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версия
                    </div>
                    <div class="card-body">
                        <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="subject-form">
                                    <td>{{ form.as_p }} </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    {% if perms.catalog.add_product %}
    <a href="{% url 'main:product_create' %}" class="btn btn-primary m-2">Создать товар</a>
    {% endif %}
    </div>
    {% include 'catalog/includes/inc_product_card.html' %}
{% endblock %}